In [1]:
import pandas as pd

C:\Users\shuto\AppData\Local\Temp\ipykernel_36476\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [6]:
store = pd.read_excel("store.xlsx")
store

,StoreId,CompleteStoreName,FoodType,AverageRating,Reviewers,City
0,echy,Chubby Taiwanese Cuisine,台灣菜,4.7,(65),Hong Kong
1,s3ul,Braza Churrascaria Brazilian Steakhouse,32分鐘,4.7,(62),Hong Kong
2,r7gr,Five Guys (Central),漢堡,4.4,(2000+),Hong Kong
3,ucgx,The Demon Celebrity,粵菜,4.0,(5),Hong Kong
4,v2xv,Carat Fine Indian Cuisine,印度菜,4.5,(89),Hong Kong
...,...,...,...,...,...,...
6232,w8tr,Eight Treasure Kitchen,Chinese,4.2,(2000+),Hong Kong
6233,k2vm,Bello Food Stop,Japanese,4.3,(100+),Hong Kong
6234,v6oh,Tsang Mei Hin,Hong Kong,4.6,(100+),Hong Kong
6235,t0fp,Mei Yuen (Tin Chak Market),Cha Chaan Teng,4.5,(1000+),Hong Kong
6236,q3xa,To-Gather,Bubble Tea,4.0,(85),Hong Kong

In [3]:
reviews = pd.read_excel("reviews.xlsx")
reviews

,StoreId,uuid,createdAt,updatedAt,text,isAnonymous,reviewerId,replies,likeCount,isLiked,overall,restaurant_food,rider
0,z7km,00006b05-61f8-4f5c-9244-00ba8d97bc0e,45074.715266,45074.715266,"味道較咸, 而且經常比漏野",False,00006b05-61f8-4f5c-9244-00ba8d97bc0e,[],1,False,2,2,NaN
1,v2nn,00017c85-e20e-4d9c-8d52-c224bf2b7d6f,45046.543403,45046.543403,出品味道實在不錯，非常欣賞大廚的烹飪\n不過樓面服務禮貌實在太差了，問多一句都不耐煩，應該生...,False,00017c85-e20e-4d9c-8d52-c224bf2b7d6f,[],0,False,1,1,NaN
2,v9tr,00026cb8-fffc-4feb-8753-1c786f71691c,45116.905914,45116.905914,Super quality and authentic.,False,hk2udxt3,[],0,False,5,5,NaN
3,h2qz,0002b618-188d-4598-a4a3-cdc4f6557f35,45343.535486,45343.535486,好味！！！,False,hkbqx1ei,[],0,False,5,5,5.0
4,u3q3,0004a723-4885-4d3e-b942-b5d3f3d02326,45286.178067,45286.178067,腸粉好硬，不過煎餃好食,False,hkkofhli,[],0,False,3,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50543,xhzo,fffc2842-8a0f-4aa7-bc80-300d6426bfd9,45228.926458,45228.926458,有個包底烘燶左，暑條好淋唔好食，雖然料好多，但品質差左好多,False,hkjg14v9,[],0,False,2,2,NaN
50544,vmgl,fffe0a1b-878a-40d8-bfd4-eefcc2f59132,45271.553461,45271.553461,肉骨茶十分十分咸,False,hkgnahje,[],0,False,1,1,NaN
50545,w7jv,fffea1e0-894f-45eb-a0f2-8f10d3d0d964,45336.914155,45336.914155,They forgot the drinks..,False,hk6jr968,[],0,False,1,1,NaN
50546,am53,ffff2d46-fce1-4d27-805a-4170d77bf4ea,45311.837708,45311.837708,炸薯條顏色偏黑，油感覺不新鮮，熱狗的包是凍的，而且有怪味,False,hkijk1ir,[],0,False,1,1,NaN
50547,w8vg,ffff4d4a-1a0f-41e9-9e47-9af5351a39fe,45344.925718,45344.925718,今次蟹棒大板燒好難食，勁喊！,False,hk855v0d,[],0,False,3,3,5.0

In [ ]:
cuisine_mapping = {
    "台灣菜": "Taiwanese",
    "漢堡": "Burgers",
    "粵菜": "Chinese",
    "印度菜": "Italian",
    "中式": "Chinese",
    "薄餅": "Pizza",
    "日式": "Japanese",
    "國際佳餚": "International",
    "西班牙菜": "Spanish",
    "西式": "Western",
    "泰國菜": "Thai",
    "意大利菜": "Italian",
    "串燒": "Skewers",
    "丼飯": "Rice Bowl",
    "蛋糕": "Cakes",
    "美式": "American"

}

In [7]:
# Function to replace Chinese names with English
def replace_food_name(food_name):
    return cuisine_mapping.get(food_name, food_name)  # Return the English name or the original if not found

# Apply the function to the food_name column
store['FoodType'] = store['FoodType'].apply(replace_food_name)

In [8]:
store

,StoreId,CompleteStoreName,FoodType,AverageRating,Reviewers,City
0,echy,Chubby Taiwanese Cuisine,Taiwanese,4.7,(65),Hong Kong
1,s3ul,Braza Churrascaria Brazilian Steakhouse,32分鐘,4.7,(62),Hong Kong
2,r7gr,Five Guys (Central),Burgers,4.4,(2000+),Hong Kong
3,ucgx,The Demon Celebrity,Chinese,4.0,(5),Hong Kong
4,v2xv,Carat Fine Indian Cuisine,Italian,4.5,(89),Hong Kong
...,...,...,...,...,...,...
6232,w8tr,Eight Treasure Kitchen,Chinese,4.2,(2000+),Hong Kong
6233,k2vm,Bello Food Stop,Japanese,4.3,(100+),Hong Kong
6234,v6oh,Tsang Mei Hin,Hong Kong,4.6,(100+),Hong Kong
6235,t0fp,Mei Yuen (Tin Chak Market),Cha Chaan Teng,4.5,(1000+),Hong Kong
6236,q3xa,To-Gather,Bubble Tea,4.0,(85),Hong Kong

In [9]:
store.columns

Index(['StoreId', 'CompleteStoreName', 'FoodType', 'AverageRating',
       'Reviewers', 'City'],
      dtype='object')

In [ ]:
# rename of the store column
store.columns = ["store_id", "complete_store_name", "food_type", "average_rating", "reviewers_count", "city"]

In [ ]:
# replace not valid food type (something mins, something 分鐘) to others
store.loc[store["food_type"].str.contains("分鐘| min"), "food_type"] = "others"

In [25]:
# cleanse reviewers_count column, removing bracket
# store["reviewers_count"].str.replace("(", "").str.replace(")", "")
store["reviewers_count"].apply(lambda x: x.replace("(", "").replace(")", ""))

0          65
1          62
2       2000+
3           5
4          89
        ...
6232    2000+
6233     100+
6234     100+
6235    1000+
6236       85
Name: reviewers_count, Length: 6237, dtype: object

In [42]:
# cleanse store name, seperate the district name 
# store["complete_store_name"].apply(lambda x: x.split("("))
store[["store_name", "district"]] = store["complete_store_name"].str.split("(", expand= True)[[0,1]]
store

,store_id,complete_store_name,food_type,average_rating,reviewers_count,city,store_name,district
0,echy,Chubby Taiwanese Cuisine,Taiwanese,4.7,(65),Hong Kong,Chubby Taiwanese Cuisine,None
1,s3ul,Braza Churrascaria Brazilian Steakhouse,others,4.7,(62),Hong Kong,Braza Churrascaria Brazilian Steakhouse,None
2,r7gr,Five Guys (Central),Burgers,4.4,(2000+),Hong Kong,Five Guys,Central)
3,ucgx,The Demon Celebrity,Chinese,4.0,(5),Hong Kong,The Demon Celebrity,None
4,v2xv,Carat Fine Indian Cuisine,Italian,4.5,(89),Hong Kong,Carat Fine Indian Cuisine,None
...,...,...,...,...,...,...,...,...
6232,w8tr,Eight Treasure Kitchen,Chinese,4.2,(2000+),Hong Kong,Eight Treasure Kitchen,None
6233,k2vm,Bello Food Stop,Japanese,4.3,(100+),Hong Kong,Bello Food Stop,None
6234,v6oh,Tsang Mei Hin,Hong Kong,4.6,(100+),Hong Kong,Tsang Mei Hin,None
6235,t0fp,Mei Yuen (Tin Chak Market),Cha Chaan Teng,4.5,(1000+),Hong Kong,Mei Yuen,Tin Chak Market)
6236,q3xa,To-Gather,Bubble Tea,4.0,(85),Hong Kong,To-Gather,None

In [51]:
# cleanse district column
store["district"] = store["district"].str.replace(")", "")

In [52]:
store

,store_id,complete_store_name,food_type,average_rating,reviewers_count,city,store_name,district
0,echy,Chubby Taiwanese Cuisine,Taiwanese,4.7,(65),Hong Kong,Chubby Taiwanese Cuisine,None
1,s3ul,Braza Churrascaria Brazilian Steakhouse,others,4.7,(62),Hong Kong,Braza Churrascaria Brazilian Steakhouse,None
2,r7gr,Five Guys (Central),Burgers,4.4,(2000+),Hong Kong,Five Guys,Central
3,ucgx,The Demon Celebrity,Chinese,4.0,(5),Hong Kong,The Demon Celebrity,None
4,v2xv,Carat Fine Indian Cuisine,Italian,4.5,(89),Hong Kong,Carat Fine Indian Cuisine,None
...,...,...,...,...,...,...,...,...
6232,w8tr,Eight Treasure Kitchen,Chinese,4.2,(2000+),Hong Kong,Eight Treasure Kitchen,None
6233,k2vm,Bello Food Stop,Japanese,4.3,(100+),Hong Kong,Bello Food Stop,None
6234,v6oh,Tsang Mei Hin,Hong Kong,4.6,(100+),Hong Kong,Tsang Mei Hin,None
6235,t0fp,Mei Yuen (Tin Chak Market),Cha Chaan Teng,4.5,(1000+),Hong Kong,Mei Yuen,Tin Chak Market
6236,q3xa,To-Gather,Bubble Tea,4.0,(85),Hong Kong,To-Gather,None